name: build

on: 
  push:
    branches:
      - main

env:
  projName: Thomas
  desc: '数空格数到吐血，这就是对人类友好吗？❤了❤了'

jobs:
  build_ubuntu:
    name: build unix binaries

    strategy:
      matrix:
        archs: [aarch64.musl, x86_64.musl]

    runs-on: ubuntu-latest
    env:
      ARCH: ${{ matrix.archs }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Docker build
        shell: bash
        run: |
          left="${ARCH%.*}"
          right="${ARCH#*.}"
          echo
          echo "${ARCH}=${left}-${right}"
          image="messense/rust-musl-cross:${left}-${right}"
          docker pull ${image}
          docker run --rm -v "$(pwd)":/home/rust/src ${image} cargo build --release --features "openssl"
          tag="${left}-unknown-linux-${right}"
          zip -q -j thomas-linux-${left}.zip target/${tag}/release/server target/${tag}/release/client

  build_windows:
    name: build windows binaries
    runs-on: windows-2019

    steps:        
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Create assets
        shell: pwsh
        run: Compress-Archive -Path target/release/*.exe thomas-win-x86_64.zip
