name: build

on: 
  push:
    branches:
      - main

env:
  projName: Thomas
  verStr: '1.1.0'
  desc: '数空格数到吐血，这就是对人类友好吗？❤了❤了'

jobs:
  build_ubuntu:
    name: build ubuntu binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Docker build
        shell: bash
        run: |
          ARCHS=('aarch64.musl' 'x86_64.musl')
          for arch in "${ARCHS[@]}"
          do
            left="${arch%.*}"
            right="${arch#*.}"
            echo
            echo "${arch}=${left}-${right}"
            image="messense/rust-musl-cross:${left}-${right}"
            docker pull ${image}
            docker run --rm -v "$(pwd)":/home/rust/src ${image} cargo build --release
            arch="${left}-unknown-linux-${right}"
            zip -q -j thomas-linux-${left}.zip target/${arch}/release/server target/${arch}/release/client
          done

  build_windows:
    name: build windows binaries
    runs-on: windows-2019

    steps:        
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Create assets
        shell: pwsh
        run: Compress-Archive -Path target/release/*.exe thomas-win-x86_64.zip
