name: main

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  projName: Thomas
  desc: '数空格数到吐血，这就是对人类友好吗？❤了❤了'

jobs:
  create_release:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      app_version: ${{ steps.gettomlver.outputs.app_version }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Get app version from Cargo.toml
        id: gettomlver
        uses: dante-signal31/rust-app-version@v1.2.0

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.gettomlver.outputs.app_version }}
          name: '${{ env.projName }} v${{ steps.gettomlver.outputs.app_version }}'
          draft: true
          prerelease: false

  build_ubuntu:
    name: Build unix binaries
    needs: create_release

    strategy:
      matrix:
        archs: [mips.musl, mipsel.musl, aarch64.musl, arm.musleabi, armv7.musleabi, i686.musl, x86_64.musl]

    runs-on: ubuntu-latest
    env:
      ARCH: ${{ matrix.archs }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Docker build
        shell: bash
        run: |
          left="${ARCH%.*}"
          right="${ARCH#*.}"
          echo
          echo "${ARCH}=${left}-${right}"
          image="messense/rust-musl-cross:${left}-${right}"
          docker pull ${image}
          docker run --rm -v "$(pwd)":/home/rust/src ${image} cargo build --release --features "openssl"
          tag="${left}-unknown-linux-${right}"
          asset="thomas-linux-${left}.zip"
          zip -q -j ${asset} target/${tag}/release/server target/${tag}/release/client

      - name: Upload unix bins
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ needs.create_release.outputs.app_version }}
          draft: true
          prerelease: false
          files: |
            thomas-linux-*.zip

  build_windows:
    name: Build windows binaries
    runs-on: windows-2019
    needs: create_release

    steps:        
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Create assets
        shell: pwsh
        run: Compress-Archive -Path target/release/*.exe thomas-win-x86_64.zip

      - name: Upload unix bins
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ needs.create_release.outputs.app_version }}
          draft: true
          prerelease: false
          files: |
            thomas-win-x86_64.zip
